try:
    print(name)
except NameError as e:
    print("Exception caught : " + str(e))


i = 2
print(i)